export interface UserProfile {
  id: string;
  name: string;
  phone: string;
  birthDate: string;
  gender: string;
  photo: string;
  notificationsEnabled: boolean;
  onboardingTourShown?: boolean;
  primaryAddressId?: string | null;
  lastAddressText?: string | null;
  lastAddressLat?: number | null;
  lastAddressLon?: number | null;
  lastAddressUpdatedAt?: string | null;
  telegramId?: number;
  favoriteCityId?: string | null;
  favoriteCityName?: string | null;
  favoriteRestaurantId?: string | null;
  favoriteRestaurantName?: string | null;
  favoriteRestaurantAddress?: string | null;
  createdAt?: string;
  updatedAt?: string;
  lastLogin?: string;
  personalDataConsentGiven?: boolean;
  personalDataConsentDate?: string | null;
  personalDataPolicyConsentGiven?: boolean;
  personalDataPolicyConsentDate?: string | null;
  isBanned?: boolean;
  bannedAt?: string | null;
  bannedReason?: string | null;
}
